wip

diff --git a/.github/workflows/test-e2e-aggOracle.yml b/.github/workflows/test-e2e-aggOracle.yml
--- a/.github/workflows/test-e2e-aggOracle.yml
+++ b/.github/workflows/test-e2e-aggOracle.yml
@@ -55,71 +55,83 @@ jobs:
     - name: Install Kurtosis CDK tools
       uses: ./kurtosis-cdk/.github/actions/setup-kurtosis-cdk
 
-    # Step to handle when the SP1_PRIVATE_KEY secret is available.
     - name: Replace Agglayer SP1 Prover Key with Github Secrets
       run: |
-        sed -i "s/agglayer_prover_sp1_key: null/agglayer_prover_sp1_key: \"${{ secrets.SP1_PRIVATE_KEY }}\"/" ${{ github.workspace }}/kurtosis-cdk/.github/tests/attach-sovereign-rollup.yml
+        sed -i "s/agglayer_prover_sp1_key: null/agglayer_prover_sp1_key: \"${{ secrets.SP1_PRIVATE_KEY }}\"/" ${{ github.workspace }}/kurtosis-cdk/.github/tests/chains/l1-cdk1-cdk2.yml
       # This step will only execute if the necessary secrets are available, preventing failures
       # on pull requests from forked repositories.
       if: ${{ env.agglayer_prover_sp1_key && env.agglayer_prover_sp1_key != '' }}
-      env :
-        agglayer_prover_sp1_key: ${{ secrets.SP1_PRIVATE_KEY }}
-
-    # Only run this step if the SP1_PRIVATE_KEY secrets is available.
-    - name: Deploy L1 and PP CDK L2 and OP Sovereign Rollup
-      if: ${{ env.agglayer_prover_sp1_key || env.agglayer_prover_sp1_key != '' }}
-      run: |
-        kurtosis run --enclave=${{ env.ENCLAVE_NAME }} --args-file=${{ github.workspace }}/kurtosis-cdk/.github/tests/attach-sovereign-rollup.yml ${{ github.workspace }}/kurtosis-cdk
       env:
         agglayer_prover_sp1_key: ${{ secrets.SP1_PRIVATE_KEY }}
 
+    - name: Deploy L1 chain, cdk-1 PP chain, and cdk-2 Sovereign chain (cdk-erigon sequencer + cdk PP stack + cdk opgeth stack)
+      run: kurtosis run --enclave=${{ env.ENCLAVE_NAME }} --args-file=${{ github.workspace }}/kurtosis-cdk/.github/tests/chains/l1-cdk1-cdk2.yml ${{ github.workspace }}/kurtosis-cdk
+
+    - name: Update the agglayer config
+      run: |
+        # Download the agglayer config file.
+        kurtosis files download ${{ env.ENCLAVE_NAME }} agglayer-config-artifact
+        cd agglayer-config-artifact
+        # Replace the agglayer config.
+        agglayer_container_id="$(docker ps --filter name=agglayer --format json | jq -r -s '. | map(select(.Names | startswith("agglayer--"))) | .[].ID')"
+        docker cp agglayer-config.toml "$agglayer_container_id:/etc/zkevm/agglayer-config.toml"
+        # Restart the agglayer service.
+        kurtosis service stop ${{ env.ENCLAVE_NAME }} agglayer
+        kurtosis service start ${{ env.ENCLAVE_NAME }} agglayer
+
     - name: Inspect enclave
       run: kurtosis enclave inspect ${{ env.ENCLAVE_NAME }}
-      if: ${{ env.agglayer_prover_sp1_key && env.agglayer_prover_sp1_key != '' }}
-      env :
-        agglayer_prover_sp1_key: ${{ secrets.SP1_PRIVATE_KEY }}
 
-    - name: Send bridge transactions from L1 to OP Sovereign L2
+    - name: Send bridge transactions from L1 to cdk-2
       if: ${{ env.agglayer_prover_sp1_key || env.agglayer_prover_sp1_key != '' }}
       working-directory: ${{ github.workspace }}/kurtosis-cdk/.github/scripts
+      shell: bash {0} # By default, GHA runs with `set -e`. This line disables that.
       run: |
-        echo "Sending a bridge transaction from L1 to the OP Sovereign RPC..."
+        echo "Sending a bridge transaction from L1 to the cdk-2 RPC..."
+        l1_rpc_url=http://$(kurtosis port print ${{ env.ENCLAVE_NAME }} el-1-geth-lighthouse rpc)
         l1_prefunded_mnemonic="giant issue aisle success illegal bike spike question tent bar rely arctic volcano long crawl hungry vocal artwork sniff fantasy very lucky have athlete"
         private_key=$(cast wallet private-key --mnemonic "$l1_prefunded_mnemonic")
         eth_address=$(cast wallet address --private-key $private_key)
-
         polycli ulxly bridge asset \
             --bridge-address 0x83F138B325164b162b320F797b57f6f7E235ABAC \
             --destination-network 2 \
             --private-key $private_key \
-            --rpc-url http://$(kurtosis port print ${{ env.ENCLAVE_NAME }} el-1-geth-lighthouse rpc) \
+            --rpc-url $l1_rpc_url \
             --value 10000000000000000000
         if [[ $ret_code -eq 0 ]]; then
-            echo "[$(date '+%Y-%m-%d %H:%M:%S')] ✅ Exiting... Deposit Transaction successfuly sent!"
+            echo "[$(date '+%Y-%m-%d %H:%M:%S')] ✅ Deposit transaction successfuly sent!"
         else
-            echo "[$(date '+%Y-%m-%d %H:%M:%S')] ❌ Exiting... Deposit Transaction failed!"
+            echo "[$(date '+%Y-%m-%d %H:%M:%S')] ❌ Deposit transaction failed!"
             exit 1
         fi
 
         echo "Waiting for deposit to be autoclaimed..."
         sleep 60
 
-        balance=$(cast balance --ether --rpc-url $(kurtosis port print ${{ env.ENCLAVE_NAME }} op-el-1-op-geth-op-node-op-kurtosis rpc) $eth_address)
-        # Use bc to compare floating-point numbers
-        result=$(echo "$balance > 0" | bc)
-        if [[ "$result" -eq 1 ]]; then
-            echo "[$(date '+%Y-%m-%d %H:%M:%S')] ✅ Deposit claimed, balance is $balance"
-        else
-            echo "[$(date '+%Y-%m-%d %H:%M:%S')] ❌ Deposit was not claimed successfully..."
-        fi
+        op_rollup_rpc_url=$(kurtosis port print ${{ env.ENCLAVE_NAME }} op-el-1-op-geth-op-node-op-kurtosis rpc)
+        while true; do
+          echo "[$(date '+%Y-%m-%d %H:%M:%S')] 🔄 Checking if the deposit was claimed..."
+          balance=$(cast balance --ether --rpc-url $op_rollup_rpc_url $eth_address)
+          result=$(echo "$balance > 0" | bc) # Use bc to compare floating-point numbers
+          if [[ "$result" -eq 1 ]]; then
+              echo "[$(date '+%Y-%m-%d %H:%M:%S')] ✅ Deposit claimed, balance is $balance"
+              exit 0
+          else
+              echo "[$(date '+%Y-%m-%d %H:%M:%S')] ❌ Deposit has not been claimed yet... Retrying in 15 seconds..."
+              sleep 15
+          fi
+        done
+
       env:
         agglayer_prover_sp1_key: ${{ secrets.SP1_PRIVATE_KEY }}
-
-    - name: Bridge from OP Sovereign L2 to L1
+  
+    - name: Bridge from cdk-2 to L1
       if: ${{ env.agglayer_prover_sp1_key || env.agglayer_prover_sp1_key != '' }}
       working-directory: ${{ github.workspace }}/kurtosis-cdk/.github/scripts
+      shell: bash {0} # By default, GHA runs with `set -e`. This line disables that.
       run: |
-        echo "Sending a bridge transaction from OP Sovereign L2 to L1..."
+        echo "Sending a bridge transaction from cdk-2 to L1..."
+        op_rollup_rpc_url=$(kurtosis port print ${{ env.ENCLAVE_NAME }} op-el-1-op-geth-op-node-op-kurtosis rpc)
         l1_prefunded_mnemonic="giant issue aisle success illegal bike spike question tent bar rely arctic volcano long crawl hungry vocal artwork sniff fantasy very lucky have athlete"
         private_key=$(cast wallet private-key --mnemonic "$l1_prefunded_mnemonic")
         eth_address=$(cast wallet address --private-key $private_key)
@@ -127,100 +139,100 @@ jobs:
             --bridge-address 0x9A1f8eA578835d2b7b1e1EB8CD5EE3Bb7692338C \
             --destination-network 0 \
             --private-key $private_key \
-            --rpc-url $(kurtosis port print ${{ env.ENCLAVE_NAME }} op-el-1-op-geth-op-node-op-kurtosis rpc) \
+            --rpc-url $op_rollup_rpc_url \
             --value $(date +%s) \
             --destination-address 0xC0FFEE0000000000000000000000000000000001
         if [[ $ret_code -eq 0 ]]; then
-            echo "[$(date '+%Y-%m-%d %H:%M:%S')] ✅ Exiting... Deposit Transaction successfuly sent!"
+            echo "[$(date '+%Y-%m-%d %H:%M:%S')] ✅ Deposit transaction successfuly sent!"
         else
-            echo "[$(date '+%Y-%m-%d %H:%M:%S')] ❌ Exiting... Deposit Transaction failed!"
+            echo "[$(date '+%Y-%m-%d %H:%M:%S')] ❌ Deposit transaction failed!"
             exit 1
         fi
 
-        echo "Waiting for deposit to be claimable..."
-        sleep 210
-
+        bridge_url=$(kurtosis port print ${{ env.ENCLAVE_NAME }} sovereign-bridge-service-001 rpc)
+        l1_rpc_url=http://$(kurtosis port print ${{ env.ENCLAVE_NAME }} el-1-geth-lighthouse rpc)
         l1_prefunded_mnemonic="giant issue aisle success illegal bike spike question tent bar rely arctic volcano long crawl hungry vocal artwork sniff fantasy very lucky have athlete"
         private_key=$(cast wallet private-key --mnemonic "$l1_prefunded_mnemonic")
         eth_address=$(cast wallet address --private-key $private_key)
-        polycli ulxly claim asset \
-            --bridge-address 0x83F138B325164b162b320F797b57f6f7E235ABAC \
-            --bridge-service-url $(kurtosis port print ${{ env.ENCLAVE_NAME }} sovereign-bridge-service-001 rpc) \
-            --deposit-count 0 \
-            --destination-address 0xc0FFee0000000000000000000000000000000001 \
-            --deposit-network 2 \
-            --private-key $private_key \
-            --rpc-url http://$(kurtosis port print ${{ env.ENCLAVE_NAME }} el-1-geth-lighthouse rpc)
-        if [[ $ret_code -eq 0 ]]; then
-            echo "[$(date '+%Y-%m-%d %H:%M:%S')] ✅ Exiting... Claim Transaction successfuly sent!"
-            exit 0
-        else
-            echo "[$(date '+%Y-%m-%d %H:%M:%S')] ❌ Exiting... Claim Transaction failed!"
-            exit 1
-        fi
+        while true; do
+          echo "[$(date '+%Y-%m-%d %H:%M:%S')] 🔄 Attempting to claim the deposit..."
+          polycli ulxly claim asset \
+              --bridge-address 0x83F138B325164b162b320F797b57f6f7E235ABAC \
+              --bridge-service-url $bridge_url \
+              --deposit-count 0 \
+              --destination-address 0xc0FFee0000000000000000000000000000000001 \
+              --deposit-network 2 \
+              --private-key $private_key \
+              --rpc-url $l1_rpc_url
+          ret_code="$?"
+          if [[ $ret_code -eq 0 ]]; then
+              echo "[$(date '+%Y-%m-%d %H:%M:%S')] ✅ Claim transaction successfuly sent!"
+              exit 0
+          else
+              echo "[$(date '+%Y-%m-%d %H:%M:%S')] ❌ Claim transaction not available for now. Retrying in 15 seconds..."
+              sleep 15
+          fi
+        done
       env:
         agglayer_prover_sp1_key: ${{ secrets.SP1_PRIVATE_KEY }}
 
-    - name: Bridge from OP Sovereign L2 to CDK L2
+    - name: Bridge from cdk-2 to cdk-1
       if: ${{ env.agglayer_prover_sp1_key || env.agglayer_prover_sp1_key != '' }}
       working-directory: ${{ github.workspace }}/kurtosis-cdk/.github/scripts
+      shell: bash {0} # By default, GHA runs with `set -e`. This line disables that.
       run: |
-        echo "Sending a bridge transaction from OP Sovereign L2 to CDK L2..."
+        echo "Sending a bridge transaction from cdk-2 to cdk-1..."
+        op_rollup_rpc_url=$(kurtosis port print ${{ env.ENCLAVE_NAME }} op-el-1-op-geth-op-node-op-kurtosis rpc)
         l1_prefunded_mnemonic="giant issue aisle success illegal bike spike question tent bar rely arctic volcano long crawl hungry vocal artwork sniff fantasy very lucky have athlete"
         private_key=$(cast wallet private-key --mnemonic "$l1_prefunded_mnemonic")
         eth_address=$(cast wallet address --private-key $private_key)
-
         polycli ulxly bridge asset \
             --bridge-address 0x9A1f8eA578835d2b7b1e1EB8CD5EE3Bb7692338C \
             --destination-network 1 \
             --private-key $private_key \
-            --rpc-url $(kurtosis port print ${{ env.ENCLAVE_NAME }} op-el-1-op-geth-op-node-op-kurtosis rpc) \
+            --rpc-url $op_rollup_rpc_url \
             --value $(date +%s) \
             --destination-address 0xC0FFEE0000000000000000000000000000000002
         if [[ $ret_code -eq 0 ]]; then
-            echo "[$(date '+%Y-%m-%d %H:%M:%S')] ✅ Exiting... Deposit Transaction successfuly sent!"
+            echo "[$(date '+%Y-%m-%d %H:%M:%S')] ✅ Deposit transaction successfuly sent!"
         else
-            echo "[$(date '+%Y-%m-%d %H:%M:%S')] ❌ Exiting... Deposit Transaction failed!"
+            echo "[$(date '+%Y-%m-%d %H:%M:%S')] ❌ Deposit transaction failed!"
             exit 1
         fi
 
-        echo "Waiting for deposit to be claimable..."
-        sleep 210
-
-        polycli ulxly claim asset \
-            --bridge-address 0x83F138B325164b162b320F797b57f6f7E235ABAC \
-            --bridge-service-url $(kurtosis port print ${{ env.ENCLAVE_NAME }} sovereign-bridge-service-001 rpc) \
-            --deposit-count 1 \
-            --destination-address 0xc0FFee0000000000000000000000000000000002 \
-            --deposit-network 2 \
-            --private-key 0x12d7de8621a77640c9241b2595ba78ce443d05e94090365ab3bb5e19df82c625 \
-            --rpc-url $(kurtosis port print ${{ env.ENCLAVE_NAME }} cdk-erigon-rpc-001 rpc) \
-            --gas-price $(cast gas-price --rpc-url $(kurtosis port print ${{ env.ENCLAVE_NAME }} cdk-erigon-rpc-001 rpc))
-        if [[ $ret_code -eq 0 ]]; then
-            echo "[$(date '+%Y-%m-%d %H:%M:%S')] ✅ Exiting... Claim Transaction successfuly sent!"
-            exit 0
-        else
-            echo "[$(date '+%Y-%m-%d %H:%M:%S')] ❌ Exiting... Claim Transaction failed!"
-            exit 1
-        fi
+        l2_rpc_url=$(kurtosis port print ${{ env.ENCLAVE_NAME }} cdk-erigon-rpc-001 rpc)
+        bridge_url=$(kurtosis port print ${{ env.ENCLAVE_NAME }} sovereign-bridge-service-001 rpc)
+        while true; do
+          echo "[$(date '+%Y-%m-%d %H:%M:%S')] 🔄 Attempting to claim the deposit..."
+          gas_price=$(cast gas-price --rpc-url $l2_rpc_url)
+          polycli ulxly claim asset \
+              --bridge-address 0x83F138B325164b162b320F797b57f6f7E235ABAC \
+              --bridge-service-url $bridge_url \
+              --deposit-count 1 \
+              --destination-address 0xc0FFee0000000000000000000000000000000002 \
+              --deposit-network 2 \
+              --private-key 0x12d7de8621a77640c9241b2595ba78ce443d05e94090365ab3bb5e19df82c625 \
+              --rpc-url $l2_rpc_url \
+              --gas-price $gas_price
+          ret_code="$?"
+          if [[ $ret_code -eq 0 ]]; then
+              echo "[$(date '+%Y-%m-%d %H:%M:%S')] ✅ Claim transaction successfuly sent!"
+              exit 0
+          else
+              echo "[$(date '+%Y-%m-%d %H:%M:%S')] ❌ Claim transaction not available for now. Retrying in 15 seconds..."
+              sleep 15
+          fi
+        done
       env:
-          agglayer_prover_sp1_key: ${{ secrets.SP1_PRIVATE_KEY }}
-    
-    - name: Dump enclave logs
-      if: failure()
-      run: kurtosis dump ./dump
+        agglayer_prover_sp1_key: ${{ secrets.SP1_PRIVATE_KEY }}
 
-    - name: Generate archive name
-      if: failure()
-      run: |
-        archive_name="dump_run_with_args_${{matrix.e2e-group}}_${{ github.run_id }}"
-        echo "ARCHIVE_NAME=${archive_name}" >> "$GITHUB_ENV"
-        echo "Generated archive name: ${archive_name}"
-        kurtosis service exec cdk cdk-node-001 'cat /etc/cdk/cdk-node-config.toml' > ./dump/cdk-node-config.toml
+    - name: Dump enclave
+      if: ${{ !cancelled() }}
+      run: kurtosis enclave dump ${{ env.ENCLAVE_NAME }} ./dump
 
-    - name: Upload logs
-      if: failure()
+    - name: Upload enclave dump
+      if: ${{ !cancelled() }}
       uses: actions/upload-artifact@v4
       with:
-        name: ${{ env.ARCHIVE_NAME }}
+        name: dump_attach_cdks_${{ github.run_id }}
         path: ./dump
